services:
    nginx:
        container_name: nginx
        build: ./nginx
        ports:
            - "8080:8080"
        depends_on:
            - backend
        restart: always
        cpus: 2
        mem_limit: 2.0g
        ulimits:
            nofile:
                soft: 200000
                hard: 200000
        sysctls:
            - net.core.somaxconn=100000
        networks:
            - keepalive-net

    backend:
        container_name: backend
        build: ./backend
        ports:
            - "8081:8080"
        cpus: 1
        mem_limit: 1.0g
        restart: always
        networks:
            - keepalive-net

    load-gen-1:
        build: ./load-test
        depends_on:
            - nginx
        cpus: 0.75
        mem_limit: 1.25g
        ulimits:
            nofile:
                soft: 100000
                hard: 100000
        networks:
            - keepalive-net

    load-gen-2:
        build: ./load-test
        depends_on:
            - nginx
        cpus: 0.75
        mem_limit: 1.25g
        ulimits:
            nofile:
                soft: 100000
                hard: 100000
        networks:
            - keepalive-net

    load-gen-3:
        build: ./load-test
        depends_on:
            - nginx
        cpus: 0.75
        mem_limit: 1.25g
        ulimits:
            nofile:
                soft: 100000
                hard: 100000
        networks:
            - keepalive-net

    load-gen-4:
        build: ./load-test
        depends_on:
            - nginx
        cpus: 0.75
        mem_limit: 1.25g
        ulimits:
            nofile:
                soft: 100000
                hard: 100000
        networks:
            - keepalive-net

networks:
    keepalive-net:
        driver: bridge
