worker_processes 2;

events {
    worker_connections 1024; 
}

http {
    upstream backend {
        server backend:8080;
    }

    server {
        listen 8080 reuseport;

        # Metrics for monitoring
        location /nginx_status {
            stub_status on;
            access_log off;
        }

        # The 'Slow' path will use GZIP at maximum level
        # This will tie up the NGINX worker process CPU.
        location /slow {
            gzip on;
            gzip_comp_level 9;
            gzip_min_length 1000;
            gzip_types text/plain;

            # Stress Test Refinement: Smaller buffers. 
            # This forces the NGINX worker to process the 50MB stream 
            # in thousands of small context-switches, creating 
            # more stutter opportunities for the event loop.
            proxy_buffers 8 4k; 
            proxy_buffer_size 4k;

            proxy_pass http://backend/slow;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            
            # Using 1.1 for keep-alive
            proxy_http_version 1.1;
            proxy_set_header Connection "";

            # Long timeouts to prevent load shedding
            proxy_read_timeout 600s;
        }

        # The 'Fast' path will have GZIP disabled
        # This serves as our probe connection to the busy worker.
        location /fast {
            gzip off;

            proxy_pass http://backend/fast;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            
            proxy_http_version 1.1;
            proxy_set_header Connection "";
        }
    }
}
