worker_processes auto;

events {
    worker_connections 1024;
}

http {
    upstream backend {
        server backend:8080;
    }

    server {
        listen 8080;

        # Metrics for the experiment (Crucial for monitoring backpressure)
        location /nginx_status {
            stub_status on;
            access_log off;
        }

        location / {
            proxy_pass http://backend;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            
            # Disable buffering to see real-time propagation
            proxy_buffering off;
        }
    }
}
