worker_processes auto;

# Experiment 7: Architect-level "No Limits"
# Removing the 1024 connection cap to observe unconstrained growth.
events {
    worker_connections 65535; 
}

# Increase physical limit of file descriptors NGINX worker can open
worker_rlimit_nofile 65535;

http {
    upstream backend {
        server backend:8080;
    }

    server {
        listen 8080;

        # Metrics for monitoring
        location /nginx_status {
            stub_status on;
            access_log off;
        }

        location / {
            proxy_pass http://backend;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            
            # Buffering is ON by default.
            # With massive buffers and 100ms backend, we force NGINX
            # to hold more state in RAM per request.
            proxy_buffering on;
            proxy_buffers 256 4k; 
            proxy_buffer_size 4k;

            # Long timeouts to prevent load shedding (we want to see it fail)
            proxy_read_timeout 600s;
            proxy_connect_timeout 600s;
        }
    }
}
